name: Rebuild documentation

on:
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      #- name: Cache pip packages
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.9'
      #    cache-dependency-path: '**/setup.py'
      #    cache: 'pip'
      
      #- name: Install pip dependencies
      #  run: pip install Sphinx 
      #    && pip install sphinx_rtd_theme 
      #    && pip install breathe
      #    && pip install exhale

      #- name: Generate doxygen-breathe-sphinx documentation
      #  run: cd doxygen_breathe_sphinx 
      #    && rm -r xml
      #    && rm -r html
      #    && rm -r documentation
      #    && rm -r exhale_documentation
      #    && mkdir documentation
      #    && mkdir exhale_documentation
      #    && sphinx-build -b html . documentation
      
      #- name: Commit changes
      #  run: git config --local user.email "test@github.com"
      #    && git config --local user.name "GitHub Action test"
      #    && git add --all
      #    && git commit -m "Rebuilt documentation"
      #    && git push

      - name: Install doxygen
        run: sudo apt-get install doxygen

      #- name: Install boost
      #  run: git clone https://github.com/bfgroup/b2.git
      #    && cd b2
      #    && ./bootstrap.sh
      #    && ./b2 install

      #- name: Install doxybook2
      #  run: mkdir db
      #    && cd db
      #    && git clone https://github.com/matusnovak/doxybook2.git
      #    && cd doxybook2
      #    && vcpkg install --triplet x64-linux $(cat vcpkg.txt)
      #    && mkdir build
      #    && cmake -B ./build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      #    && cmake --build ./build --config MinSizeRel
      #    && cd

      - name: Install doxybook2
        run: curl -s https://api.github.com/repos/matusnovak/doxybook2/releases/latest | jq -r ".assets[] | select(.name | test(\"${linux_amd64}\")) | .browser_download_url"
      
      - name: Generate doxygen xml documentation
        run: cd doxygen_breathe_sphinx 
          && mkdir doxygen_xml
          && doxyygen

      - name: Convert xml to md using doxybook2
        run: mkdir doxybook_md
          && ../doxybook2/build/MinSizeRel/doxybook2 -i ./xml -o ./doxybook_md -c ./config.json -t ./doxybook_templates

      - name: Push generated html to site repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'doxygen_breathe_sphinx/doxybook_md'
          destination-github-username: 'RC1242RC'
          destination-repository-name: 'RC1242RC.github.io'
          user-email: r.clark1242@gmail.com
          target-branch: master
          target-directory: content/en/documentation/code
      
      - name: Trigger site rebuild
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PUBLIC_REPO }}
          repository: RC1242RC/RC1242RC.github.io
          event-type: documentation_rebuilt
